- · 随机生成的数组  
-· 元素级操作  
- 比较操作  
-· 逻辑操作.总结操作

# 一维数组

In [2]:
import numpy as np
np.zeros(10) # 创建10个元素，值都为0，的数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)  # 创建10个元素，值都为1的数组

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,2.5) #创建10个元素，值都为2.5的数组

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,5,7,12])  # 用array 函数，创建数组
a

array([ 1,  2,  3,  5,  7, 12])

In [8]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [10]:
np.arange(10) #  创建10个元素的数组，范围是0-9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(3,10) #  创建10个元素的数组，范围是3-9

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,100,11) #创建1个数组，共11个元素，从0开始，最大100）

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# 二维数组

In [14]:
np.zeros((5,2))  # 创建1个5行两列的二位数组

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
n[0,1] = 20
print(n)
n[0,1]

[[ 1 20  5]
 [ 4  5  8]
 [ 7  8 11]]


np.int64(20)

In [8]:
n[:,1]   # 冒号表示所有行，1表示第2列

array([20,  5,  8])

In [6]:
n[:,2] = [5,8,11]
n

array([[ 1,  2,  5],
       [ 4,  5,  8],
       [ 7,  8, 11]])

# 随机数组

In [32]:
np.random.seed(2)   #固定随机数种子
100*np.random.rand(5,2) #5行2列的随机数，如果不用100相乘，那么得到的随机树，就是默认0-1范围的

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [31]:
np.random.seed(2)   #固定随机数种子
np.random.randn(5,2) #5行2列的随机数，正态分布的随机树

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [33]:
np.random.seed(2)   #固定随机数种子
np.random.randint(low=0,high=100,size=(5,2)) #5行2列的随机数，最小零，最大100

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# 元素级操作

In [4]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
a + 1   #numpy 数组，可以直接给每个元素加1，如果是python的原始array，则需要写循环来实现

array([1, 2, 3, 4, 5])

In [39]:
b = (10+(a*2))**2 / 100
print(b)
a + b

[1.   1.44 1.96 2.56 3.24]


array([1.  , 2.44, 3.96, 5.56, 7.24])

# 比较操作

In [40]:
a > 2

array([False, False, False,  True,  True])

In [41]:
a > b

array([False, False,  True,  True,  True])

In [42]:
a[a > b]  # 返回a数组中，满足a大于b的情况的元素 

array([2, 3, 4])

# 汇总操作

In [43]:
n.sum()

np.int64(69)

In [44]:
a.std()

np.float64(1.4142135623730951)

In [46]:
a.max()

np.int64(4)

In [47]:
a.min()

np.int64(0)