# vector operations   向量操作


In [2]:
import numpy as np

In [3]:
u = np.array([2,4,5,6])

In [4]:
2 * u

array([ 4,  8, 10, 12])

In [5]:
v = np.array([1,0,0,2])

In [6]:
u + v

array([3, 4, 5, 8])

In [7]:
u * v

array([ 2,  0,  0, 12])

# Multiplication 乘法

In [14]:
u

array([2, 4, 5, 6])

In [15]:
u.shape  # shape是数组内的元素数量 ，结果是一个元组

(4,)

In [18]:
u.shape[0] #  shape[0] 是取数组的形状信息——也就是第一维的长度

4

In [12]:
# 编写1个函数，来进行向量乘法
def vector_vector_multiplication(u,v):
    assert  u.shape[0] == v.shape[0]  # 检查向量形状 # 断言条件成立，如果不成立，程序立刻崩溃报错

    n = u.shape[0] 
    result = 0.0 
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [13]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [19]:
u.dot(v)  #numpy中的点积乘法

np.int64(14)

In [22]:
U = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])

In [26]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [25]:
U.shape

(3, 4)

In [28]:
U.shape[0]

3

## matirx_vector_Multiplication  矩阵向量乘法

In [32]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]  # 判断矩阵的列数，与向量元素是否相等，表示矩阵和向量相乘，即是向量乘以矩阵的每一行
    num_rows = U.shape[0] 
    result = np.zeros(num_rows)
    for i in range(num_rows):
       result[i] = vector_vector_multiplication(U[i],v) 
    return result

In [33]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [34]:
U.dot(v)   #numpy中的点积乘法 ,结果是一样的。

array([14,  5,  5])

## 矩阵乘法 # 关键是，两个矩阵中，1个的行的shape的值，与1个的列shape的值，是要一样的

In [37]:
V = np.array([[1,1,2],[0,0.5,1],[0,2,1],[2,1,0]])

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [39]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [57]:
V.shape

(4, 3)

In [42]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0] # 判断矩阵的行列是否相等，表示矩阵相乘即是 列乘以行
    num_rows = U.shape[0] 
    num_cols = V.shape[1] 
    result = np.zeros((num_rows,num_cols)) # 3行3列的矩阵

    for i in range(num_cols):
        vi = V[:,i]
        Uvi = matirx_vector_multiplication(U,vi)
        result[:,i] = Uvi
    return result

In [43]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [59]:
U.shape
V.shape
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# identity matrix     单位矩阵  用I表示
对角线上的元素都是1，其余元素都是0
像这样的：
1 0 0 0 

0 1 0 0 

0 0 1 0 

0 0 0 1 

U * I = U
单位矩阵就像是数字1 

In [53]:
I = np.eye(3)  # 创建单位矩阵
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

# matrix  inverse  矩阵逆：一个矩阵的逆矩阵，当它与原矩阵相乘时，结果为***单位矩阵***。
***只有方阵才有逆矩阵***

In [61]:
Vs = V[[0,1,2]]  #把V矩阵中的1，2，3行取出来，就是3*3的方阵
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [62]:
Vs_inv = np.linalg.inv(Vs)  # 求Vs的逆矩阵 
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [63]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

***矩阵逆的逻辑，对于线性回归非常有用***